### PR TITLE
Restrict file extensions that may contain JSX

### PR DESCRIPTION
**Pull request by hitochan777**
All files that contain JSX-specific syntax must have `.jsx` extension so that it is easy to know if a file contains React components or not.

https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-filename-extension.md

### CODE REVIEW

**Comment by hitochan777** [comment]
Let me know your thought on this.

**Comment by willjw3** [comment]
So, all page files that use React components and all React component files themselves?

**Comment by hitochan777** [comment]
@willjw3 Yes

**Review by willjw3 — APPROVED** [review]
This is fine with me as long as no one else has any objections.

**Comment by willjw3** [comment]
So, will you change the extensions of the appropriate existing files in the 'develop' branch, @hitochan777 ?

**Comment by hitochan777** [comment]
@willjw3 I have already done that.

**Comment by willjw3** [comment]
@hitochan777 Thanks!

**Pull request merged**
