### PR TITLE
Continuous Integration with Now.sh

### LINKED ISSUE #48: Continuous Integration with Now.sh

### PR DESCRIPTION
**Pull request by hitochan777**
Fixes #48

### CODE REVIEW

**Comment by hitochan777** [comment]
@willjw3 @allanapplebee @picklu 
It turned out that I need to make client and server independent to deploy them on now.sh.
It means that we will have package.json for each directory and serve next.js app with the server provided by next, rather than with our express server.
It will change the directory structure a bit. Is it ok?

**Comment by willjw3** [comment]
> @willjw3 @allanapplebee @picklu
> It turned out that I need to make client and server independent to deploy them on now.sh.
> It means that we will have package.json for each directory and serve next.js app with the server provided by next, rather than with our express server.
> It will change the directory structure a bit. Is it ok?

Does this mean we'll have to update the import file paths in some of our files?

**Comment by hitochan777** [comment]
@willjw3 There are very few parts where a client side file imports a server side file, and visa-versa. So I believe you don't have to. If any, very few.

**Comment by willjw3** [comment]
> It turned out that I need to make client and server independent to deploy them on now.sh.
> It means that we will have package.json for each directory and serve next.js app with the server provided by next, rather than with our express server.
> It will change the directory structure a bit. Is it ok?

I'm Ok with it.

**Comment by hitochan777** [comment]
I give up on Now.sh for now because it does not seem to support async generator syntax which is available from node 10.x

**Pull request closed without merging**
