### PR TITLE
[WIP] Setup Continuous Deployment

### LINKED ISSUE #7: Continuous Deployment

### PR DESCRIPTION
**Pull request by hitochan777**
Fixes #7

### CODE REVIEW

**Comment by hitochan777** [comment]
In order for each PR to have its own heroku environment (it's called [Review App](https://devcenter.heroku.com/articles/github-integration-review-apps#setup)), we need to add `app.json` (setting file for heroku) to `develop` branch.

**Comment by hitochan777** [comment]
@allanapplebee I don't think you have to change CircleCI. All you need to do is enable automatic deployment for each app in a heroku pipeline.
Here's what I have done in heroku setting so far:
- Change `chingu-bears-06-test` to `chingu-bears-06-staging` because it makes more sense
- Auto deploy `develop` branch  to `chingu-bears-06-staging` app when CircleCI test passes
- Auto deploy `master` branch  to `chingu-bears-06-prod` app when CircleCI test passes

**Comment by allanapplebee** [comment]
@hitochan777 thanks for this. The issue I've been having isn't that it won't build properly, but when you go to the actual site, it isn't working. 

Go to https://chingu-bears-06-staging.herokuapp.com/ and you just see application error.

run` heroku logs --app=chingu-bears-06-staging` for the logs

**Comment by allanapplebee** [comment]
Sorry, jumped the gun...have linting errors i need to sort out before the review!

**Comment by allanapplebee** [comment]
should be good to go now :)

**Pull request closed without merging**
